global:
  postgresql:
    auth:
      postgresPassword: ${POSTGRES_PASSWORD}
      database: smartdinings
primary:
  persistence:
    storageClass: "longhorn"
    size: 8Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m