auth:
   password: ${REDIS_PASSWORD}
master:
   persistence:
      storageClass: "longhorn"
      size: 8Gi
   resources:
      requests:
         memory: 128Mi
         cpu: 100m
      limits:
         memory: 256Mi
         cpu: 250m
replica:
   persistence:
      storageClass: "longhorn"
      size: 8Gi
   resources:
      requests:
         memory: 128Mi
         cpu: 100m
      limits:
         memory: 256Mi
         cpu: 250m