apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgvector.fullname" . }}-config
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
data:
  POSTGRES_DB: '{{ .Values.pgVector.database }}'
  POSTGRES_USER: '{{ .Values.pgVector.username }}'