apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgvector.fullname" . }}
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.pgVector.password | b64enc | quote }}