apiVersion: v1
kind: Secret
metadata:
  name: milvus-secret
type: Opaque
stringData:
  rootCoordinator-address: milvus-root-coord
  rootCoordinator-port: "19530"
  etcd-endpoints: milvus-etcd:2379
  pulsar-address: pulsar://milvus-pulsar:6650
  minio-address: milvus-minio:9000
  minio-accessKey: ${MINIO_ACCESS_KEY}
  minio-secretKey: ${MINIO_SECRET_KEY}